### ISSUE TITLE
check for blocking locks

### ISSUE THREAD

**Issue by miraclesvenni** [bucardo/check_postgres#154]
[lockwait.patch.zip](https://github.com/bucardo/check_postgres/files/2649719/lockwait.patch.zip)

Added a check I thought was missing.

It checks for locks which have been blocking for more than specified time.

Tested on 9.6 and 10.6

**Comment by machack666** [comment]
Hi @miraclesvenni — is there a minimum version for this check?  If so I'd love to see a check to enforce that.

**Comment by omacchioni** [comment]
Hello @machack666 

I have tested the SQL, it works on 9.4.24 and 10.10. So it probably works for all versions between those.

As 9.3 is not supported any more since 2018, I assume it's OK to state that we need 9.4 for this patch and not go back in time to see if it works with 9.3.

I have to add that this patch is really of value for us - `--action locks` option only tells you there are locks, which are not an issue by themselves - so you get a lot of false positives. The alternative implemented is this patch is actually telling you that some requests are blocked, and that's 95% of the issues we get in production where I work.
