### ISSUE TITLE
Issue with database having a "-" in their names in function check_locks

### ISSUE THREAD

**Issue by srosog** [bucardo/check_postgres#93]
Hello,

When I try to get locks from a database that has a hyphen in its name, an error occurs :
```
# check_postgres.pl --dbuser=xxx --dbservice=SRV-01_db-01 --action=locks --include=db-01
POSTGRES_LOCKS UNKNOWN: service=SRV-01_db-01 No matching databases found due to exclusion/inclusion options | time=0.04
```

It seems to come from the line 3525 :
```SLURP: while ($db->{slurp} =~ /([tf])\s*\|\s*(\w+)\s*\|\s*(\w+)\s+/gsm) {```

The final \w+ (which corresponds to $3) does not match, because \w only matchs a "word" character (alphanumeric plus "_").

Best regards

Stefan

**Comment by glynastill** [comment]
Which version is this on?  Unless I'm mistaken line 3525 in HEAD and the archive on bucardo.org differ from what you've noted above.

In version 2.21.0 hyphens appear to work fine for me;

./check_postgres.pl --dbuser=xxx --dbname=db-01 --action=locks --include=db-01
POSTGRES_LOCKS OK: DB "db-01" total=1  | time=2.03s db-01.total=1;100;150

I did notice that if you connect to a database that you don't include in the include list you get:

./check_postgres.pl --dbuser=xxx --dbname=postgres --action=locks --include=db-01
POSTGRES_LOCKS UNKNOWN: DB "postgres" No matching databases found due to exclusion/inclusion options | time=1.66s db-01.total=0;100;150

Which is a bit misleading, but the locks in the included database are shown.  Perhaps you're seeing something similar with your service file?

I don't think we're talking about the same issue here, but I think doing soemthing like this https://github.com/glynastill/check_postgres/commit/50a7e3ca469770cee401bdd763c3415a2291f7f5 makes it less confusing:

./check_postgres.pl --dbuser=xxx --dbname=postgres --action=locks --include=db-01
POSTGRES_LOCKS OK: DB "postgres" total=0  | time=1.92s db-01.total=0;100;150

**Comment by srosog** [comment]
Hello,

My apologies, we took the latest version on Nagios Exchange, which is 2.11.1.
https://exchange.nagios.org/directory/Plugins/Databases/PostgresQL/check_postgres/details

We tried the latest version on bucardo.org, and the issue is fixed indeed.

**Comment by gsssathe** [comment]
I am using the version 2.22.0 . But am facing the same issue for table_size.

./check_postgres.pl --host=<ServerName> --port=5444 --dbname=XXXX --dbuser=YYYY --dbpass=ZZZZ  --action=table_size -w 80 -c 90 --include=public

Am getting error as 
POSTGRES_TABLE_SIZE UNKNOWN: DB "XXXX" (host:ServerName) (port=5444) No matching relations found due to exclusion/inclusion options | time=0.01s
